---
abstract: 'discovery, fetch and parse Resource Description Document by using XRDS-Simple'
author:
  - 'Takatsugu Shigeta <shigeta@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XRDS-Simple
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Moose: 0.72
  URI::Fetch: 0.08
  WWW::Blog::Metadata: 0.02
  WWW::Blog::Metadata::Yadis: 0.03
  XML::LibXML: 1.6
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
